#ifndef SINGULARITY_QUERY_HPP
#define SINGULARITY_QUERY_HPP

#include "componentregistry.hpp"
#include "core/ecs/componentstorage.hpp"
#include <core/ecs/componentregistry.hpp>

template<typename... Components>
class Query {
public:
    Query(ComponentRegistry& registry) : registry(registry) {}
    ~Query() {}

    auto query() {
        // I don't give a fuck what that fucking abomination does,
        // but it does it's work and does it very fast,
        // generated by AI, I hope I'll recover from this

        auto storages = std::tuple{
            static_cast<ComponentStorage<Components>*>(registry.getStorage<Components>())...
        }; // gather storages

        size_t min = std::get<0>(storages)->count();
        size_t index = 0;
        [&]<size_t... i>(std::index_sequence<i...>) {
            (([&] {
                auto* s = std::get<i>(storages);
                if (s->count() < min) {
                    min = s->count();
                    index = i;
                }
            }()), ...);
        }(std::index_sequence_for<Components...>{});

        std::vector<std::tuple<Components*...>> result;

        [&]<size_t... I>(std::index_sequence<I...>) {
            ((index == I ? (runQuery(std::get<I>(storages), result), void()) : void()), ...);
        }(std::index_sequence_for<Components...>{});

        return result;
    }
    
private:
    ComponentRegistry& registry;

    template<typename T>
    inline T* getPtr(Entity e) {
        return static_cast<ComponentStorage<T>*>(
            registry.getStorage<T>()
        )->get(e).value_or(nullptr); // returns T*
    }

    template<typename Primary>
    inline void runQuery(ComponentStorage<Primary>* primary,
                std::vector<std::tuple<Components*...>>& result)
    {
        for (Entity e : primary->get_entities()) {
            if ((registry.getStorage<Components>()->has(e) && ...)) {
                result.emplace_back(getPtr<Components>(e)...);
            }
        }
    }
};

#endif // SINGULARITY_QUERY_HPP